CREATE DATABASE PELUQUERIA_CANINA;
USE PELUQUERIA_CANINA;
CREATE TABLE DUENO (
DNI INT NOT NULL,
NOMBRE VARCHAR(70) NOT NULL,
APELLIDO VARCHAR(55) NOT NULL,
TELEFONO VARCHAR(48) NOT NULL,
DIRECCION VARCHAR(300) DEFAULT NULL,
PRIMARY KEY(DNI)
);
CREATE TABLE PERRO (
ID_PERRO INT NOT NULL auto_increment,
NOMBRE VARCHAR(70) DEFAULT NULL,
FECHA_NAC date,
SEXO VARCHAR(50) default NULL,
DNI_DUENO INT NOT NULL,
PRIMARY KEY(ID_PERRO),
FOREIGN KEY(DNI_DUENO) REFERENCES DUENO(DNI),
INDEX IDX_NOMPERRO(NOMBRE)
);
 CREATE TABLE HISTORIAL (
 ID_HISTORIAL INT NOT NULL AUTO_INCREMENT,
 FECHA DATE,
 PERRO VARCHAR(70) DEFAULT NULL,
 DESCRIPCION VARCHAR(50) DEFAULT NULL,
 MONTO INT DEFAULT NULL,
 PRIMARY KEY (ID_HISTORIAL),
 FOREIGN KEY (PERRO) REFERENCES PERRO(NOMBRE)
);

INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (41521949, "NAHUEL", "MOLINA", 3512455803, "CALLE SAN MARTIN 150, CORDOBA");
INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (38182463, "FLORENCIA", "OLIMA", 3512564839, "CALLE BOLIVIA 563, CORDOBA");
INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (40563843, "PEDRO", "PEREZ", 3516485733, "CALLE BS AS 896, CORDOBA");
INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (30247041, "JOSE", "ALONZO", 3512458798, "CALLE RIO PRIMERO 69, CORDOBA");

INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("LUNA", "28-03-2018", "HEMBRA", 41521949 );
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("ZEUS", "03-05-2023", "MACHO", 38182463 );
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("MARRON", "20-11-2020", "MACHO", 40563843 );
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("MURDO", "19-10-2019", "MACHO", 30247041 );

INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2012-01-30", "LUNA", "MESTIZO", 6000 );
INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2005-11-15", "ZEUS", "CANICHE", 8000 );
INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2022-05-10", "MARRON", "PASTOR ALEMAN", 7000 );
INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2005-11-15", "MURDO", "DOGO", 5800 );

#EJERCICIO 12#
SELECT NOMBRE FROM PERRO
WHERE SEXO = "MACHO" AND DATE (FECHA_NAC) >='2020-01-01'
AND DATE (FECHA_NAC) <='2022-01-01';


