CREATE DATABASE PELUQUERIA_CANINA;
USE PELUQUERIA_CANINA;
CREATE TABLE PERRO (
ID_PERRO INT NOT NULL auto_increment,
NOMBRE VARCHAR(225) DEFAULT NULL,
FECHA_NAC date,
SEXO VARCHAR(30) default NULL,
DNI_DUENO INT NOT NULL,
PRIMARY KEY(ID_PERRO),
FOREIGN KEY(DNI_DUENO) REFERENCES DUENO(DNI),
INDEX IDX_NOMPERRO(NOMBRE)
);
CREATE TABLE DUENO(
DNI INT NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL,
TELEFONO INT DEFAULT NULL,
DIRECCION VARCHAR(225) DEFAULT NULL,
PRIMARY KEY(DNI)
);
 CREATE TABLE HISTORIAL (
 ID_HISTORIAL INT NOT NULL AUTO_INCREMENT,
 FECHA DATE,
 PERRO VARCHAR(225) DEFAULT NULL,
 DESCRIPCION VARCHAR(500) DEFAULT NULL,
 MONTO INT DEFAULT NULL,
 PRIMARY KEY (ID_HISTORIAL),
 FOREIGN KEY (PERRO) REFERENCES PERRO(NOMBRE)
);

INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (19023456, "PEDRO", "GARCIA", 112345678, "CALLE ECHEVERRIA N° 1341, CORDOBA");
INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (19234654, "PABLO", "SANCHEZ", 115467890, "CALLE PASO DE USPALLATA N° 633, CORDOBA");
INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (21346974, "PEDRO", "PEREZ", 112334578, "CALLE AVENIDA ALBARELLOS N° 2915, CABA");
INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (30247041, "ROGER", "ESCUDERO", 115347890, "CALLE DONATO ALVAREZ N° 3536, CABA");
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("MIGUEL", "2016-04-24", "MACHO", 19023456 );
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("CHIKI", "2012-02-12", "HEMBRA", 19234654 );
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("OBI", "2020-11-20", "HEMBRA", 21346974 );
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("TOMI", "2021-09-11", "MACHO", 30247041 );

INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2012-01-30", "MIGUEL", "DOBERMAN", 3500 );
INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2005-11-15", "CHIKI", "CANICHE", 5600 );
INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2022-05-10", "OBI", "DOBERMAN", 7000 );
INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2005-11-15", "TOMI", "MESTIZO", 1200 );

# Ejercicio 5: Realice una consulta multitabla que arroje el nombre de todos los perros cuyos dueños se llaman Pedro# 
select p.NOMBRE
FROM perro p join dueno d on
p.DNI_DUENO=d.DNI
where d.NOMBRE= 'Pedro'
