CREATE DATABASE PELUQUERIA_CANINA;
USE PELUQUERIA_CANINA;
CREATE TABLE DUENO(
DNI INT NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
TELEFONO INT DEFAULT NULL,
DIRECCION VARCHAR(100) DEFAULT NULL,
PRIMARY KEY(DNI)
);
CREATE TABLE PERRO (
ID_PERRO INT NOT NULL auto_increment,
NOMBRE VARCHAR(30) DEFAULT NULL,
FECHA_NAC date,
SEXO VARCHAR(20) default NULL,
DNI_DUENO INT NOT NULL,
PRIMARY KEY(ID_PERRO),
FOREIGN KEY(DNI_DUENO) REFERENCES DUENO(DNI),
INDEX IDX_NOMPERRO(NOMBRE)
);
 CREATE TABLE HISTORIAL (
 ID_HISTORIAL INT NOT NULL AUTO_INCREMENT,
 FECHA DATE,
 PERRO VARCHAR(100) DEFAULT NULL,
 DESCRIPCION VARCHAR(500) DEFAULT NULL,
 MONTO INT DEFAULT NULL,
 PRIMARY KEY (ID_HISTORIAL),
 FOREIGN KEY (PERRO) REFERENCES PERRO(NOMBRE)
);

INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (30971496, "DESIREE", "MINGORANCE", 3516789076, "CALLE ECUADOR 847, CORDOBA");
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("MELON", "2017-05-11", "MACHO", 30971496 );

INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (53509501, "ISMAEL", "LORENZO", 3515768905, "CALLE SOTO 2346, CORDOBA");
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("URITORCO", "2014-03-20", "MACHO", 53509501 );

INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (48567890, "LUCAS", "SANCHEZ", 3513678932, "CALLE EE UU 4326, CORDOBA");
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("SAMURAI", "2021-04-18", "MACHO", 48567890 );

INSERT INTO DUENO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (30846599, "SAUL", "ORTEGA", 3515786543, "CALLE MARTIN CARTECHINI 1844, CORDOBA");
INSERT INTO PERRO (NOMBRE, FECHA_NAC, SEXO, DNI_DUENO) VALUES ("SOFIA", "2018-07-14", "HEMBRA", 30846599 );

INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2017-06-12", "MELON", "CANICHE", 5600 );
INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2014-04-30", "URITORCO", "DOBERMAN", 7500 );
INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2021-05-30", "SAMURAI", "PASTOR ALEMAN", 7000 );
INSERT INTO HISTORIAL (FECHA, PERRO, DESCRIPCION, MONTO) VALUES ("2018-08-20", "SOFIA", "MESTIZO", 4500 );

#EJERCICIO 9#
SELECT * FROM DUENO;
UPDATE DUENO SET DIRECCION = "LIBERTAD 123" WHERE DNI =30971496;
